---
- include_tasks: install_python_from_ius.yml
  when: ansible_distribution == 'Amazon' and ansible_service_mgr == 'upstart' or ansible_distribution == 'CentOS' and ansible_distribution_major_version is version("7", "<=")

- include_tasks: install_python_for_rhel8.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version is version("8", ">=")
